// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';


// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';


//reclamtion
export const RECLAMATION_LOADING = 'RECLAMATION_LOADING';
export const GET_RECLAMATION = 'GET_RECLAMATION';
export const GET_RECLAMATIONS = 'GET_RECLAMATIONS';
export const ADD_RECLAMATION = 'ADD_RECLAMATION';
export const DELETE_RECLAMATION = 'DELETE_RECLAMATION';
export const SEARCH_RECLAMATION = 'SEARCH_RECLAMATION';
export const EDIT_RECLAMATION = 'EDIT_RECLAMATION';
export const GET_INACTIVE_RECLAMATION = 'GET_INACTIVE_RECLAMATION';
export const ARCHIVE_RECLAMATION = 'ARCHIVE_RECLAMATION';
export const UNARCHIVE_RECLAMATION = 'UNARCHIVE_RECLAMATION';
export const IS_MODIFIED_RECLAMATION = 'IS_MODIFIED_RECLAMATION';

